pet_adoption/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import (
    RegisterView,
    UserProfileDetailView,
    UserProfileUpdateView,
)

app_name = "accounts"

urlpatterns = [
    path(
        "userprofile/<int:pk>/",
        UserProfileDetailView.as_view(),
        name="userprofile_detail",
    ),
    path(
        "userprofile/<int:pk>/update/",
        UserProfileUpdateView.as_view(),
        name="userprofile_update",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/register/", RegisterView.as_view(), name="register"),
]

pet_adoption/pet/urls.py
from django.urls import path
from pet.views import (
    HomeView,
    AboutView,
    DonateView,
    MyPetsView,
    AvailableServicesView,
    CreateServiceView,
    AvailableTreatmentsView,
    CreateTreatmentView,
    FindCatsView,
    FindDogsView,
    FindOtherPetsView,
    FindAllView,
    AnimalDetailView,
    CreateAdoptionView,
    AdoptionStoriesView,
    AdoptionPendingListView,
    ApproveAdoptionView,
    AddAdoptionStoryView,
    AnimalFavouriteListView,
    MyAdoptionFormsView,
    AnimalSearchView,
)


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("donate/", DonateView.as_view(), name="donate"),
    path("about/", AboutView.as_view(), name="about"),
    path("animal_search/", AnimalSearchView.as_view(), name="animal_search"),
    path(
        "animal_detail/<int:animal_id>/",
        AnimalDetailView.as_view(),
        name="animal_detail",
    ),
    path("my_pets/", MyPetsView.as_view(), name="my_pets"),
    path("my_adoption_forms/", MyAdoptionFormsView.as_view(), name="my_adoption_forms"),
    path("services/<int:pk>/", AvailableServicesView.as_view(), name="services"),
    path(
        "services/create/<int:animal_id>/",
        CreateServiceView.as_view(),
        name="create_service",
    ),
    path("treatments/<int:pk>/", AvailableTreatmentsView.as_view(), name="treatments"),
    path(
        "treatments/create/<int:animal_id>/",
        CreateTreatmentView.as_view(),
        name="create_treatment",
    ),
    path("cats/find/", FindCatsView.as_view(), name="find_cats"),
    path("dogs/find/", FindDogsView.as_view(), name="find_dogs"),
    path("other_pets/find/", FindOtherPetsView.as_view(), name="find_other_pets"),
    path("all_pets/find/", FindAllView.as_view(), name="find_all_pets"),
    path("adoption/create/", CreateAdoptionView.as_view(), name="create_adoption"),
    path(
        "adoption/pending/",
        AdoptionPendingListView.as_view(),
        name="adoption_pending_list",
    ),
    path(
        "adoption/<int:pk>/approve/",
        ApproveAdoptionView.as_view(),
        name="approve_adoption",
    ),
    path(
        "adoption/story/<int:adoption_pk>/add/",
        AddAdoptionStoryView.as_view(),
        name="add_adoption_story",
    ),
    path("adoption/stories/", AdoptionStoriesView.as_view(), name="adoption_stories"),
    path(
        "favourites/", AnimalFavouriteListView.as_view(), name="animal_favourite_list"
    ),
]

pet_adoption/pet_adoption/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pet.urls")),
    path("", include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pet_adoption/pet/views.py
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView, DetailView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from pet.forms import (
    CustomUserCreationForm,
    ServiceForm,
    TreatmentForm,
    AnimalFilterForm,
    AdoptionForm,
    AdoptionStoryForm,
)
from pet.models import (
    Animal,
    Service,
    Treatment,
    Adoption,
    AdoptionStory,
)


class HomeView(TemplateView):
    """
    A view for the home page.

    Attributes:
        template_name (str): The template name to render for the home page.

    Methods:
        get_context_data(**kwargs): Overrides the default get_context_data method to provide context data to the template.
    """

    template_name = "home.html"

    def get_context_data(self, **kwargs):
        """
        Provide context data to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for rendering the template.
        """

        context = super().get_context_data(**kwargs)

        animals = Animal.objects.filter(is_available_for_adoption=True)
        adoption_stories = AdoptionStory.objects.all()
        available_animals = animals.count()

        context["animals"] = animals
        context["adoption_stories"] = adoption_stories
        context["available_animals"] = available_animals

        if self.request.user.is_authenticated:
            try:
                user_location = self.request.user.location
                animals_near_user = animals.filter(location=user_location)
                context["animals_near_user"] = animals_near_user
                context["user_location"] = user_location
            except AttributeError:
                context["user_location"] = ""

        return context


class FindAllView(TemplateView):
    """
    A view for finding and filtering available pets.

    Attributes:
        template_name (str): The template name to render for the page.

    Methods:
        get_context_data(**kwargs): Overrides the default get_context_data method to provide context data to the template.
    """

    template_name = "find_all.html"

    def get_context_data(self, **kwargs):
        """
        Provide context data to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for rendering the template.
        """

        context = super().get_context_data(**kwargs)
        all_pets = Animal.objects.filter(is_available_for_adoption=True)

        filter_form = AnimalFilterForm(self.request.GET)
        if filter_form.is_valid():
            species = filter_form.cleaned_data.get("species")
            breed = filter_form.cleaned_data.get("breed")
            gender = filter_form.cleaned_data.get("gender")
            size = filter_form.cleaned_data.get("size")
            color = filter_form.cleaned_data.get("color")
            min_age = filter_form.cleaned_data.get("min_age")
            max_age = filter_form.cleaned_data.get("max_age")
            location = filter_form.cleaned_data.get("location")

            if species:
                all_pets = all_pets.filter(species__icontains=species)
            if breed:
                all_pets = all_pets.filter(breed__icontains=breed)
            if gender:
                all_pets = all_pets.filter(gender=gender)
            if size:
                all_pets = all_pets.filter(size=size)
            if color:
                all_pets = all_pets.filter(color__icontains=color)
            if min_age:
                all_pets = all_pets.filter(age__gte=min_age)
            if max_age:
                all_pets = all_pets.filter(age__lte=max_age)
            if location:
                all_pets = all_pets.filter(location=location)

        context["all_pets"] = all_pets
        context["filter_form"] = filter_form
        return context


class FindCatsView(TemplateView):
    """
    A view for finding and filtering available cats.

    Attributes:
        template_name (str): The template name to render for the page.

    Methods:
        get_context_data(**kwargs): Overrides the default get_context_data method to provide context data to the template.
    """

    template_name = "find_cats.html"

    def get_context_data(self, **kwargs):
        """
        Provide context data to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for rendering the template.
        """

        context = super().get_context_data(**kwargs)

        cats = Animal.objects.filter(
            species__iexact="cat", is_available_for_adoption=True
        )

        show_species = False
        filter_form = AnimalFilterForm(self.request.GET, show_species=show_species)
        if filter_form.is_valid():
            breed = filter_form.cleaned_data.get("breed")
            gender = filter_form.cleaned_data.get("gender")
            size = filter_form.cleaned_data.get("size")
            color = filter_form.cleaned_data.get("color")
            min_age = filter_form.cleaned_data.get("min_age")
            max_age = filter_form.cleaned_data.get("max_age")
            location = filter_form.cleaned_data.get("location")

            if breed:
                cats = cats.filter(breed__icontains=breed)
            if gender:
                cats = cats.filter(gender=gender)
            if size:
                cats = cats.filter(size=size)
            if color:
                cats = cats.filter(color__icontains=color)
            if min_age:
                cats = cats.filter(age__gte=min_age)
            if max_age:
                cats = cats.filter(age__lte=max_age)
            if location:
                cats = cats.filter(location=location)

        context["cats"] = cats
        context["filter_form"] = filter_form
        return context


class FindDogsView(TemplateView):
    """
    A view for finding and filtering available dogs.

    Attributes:
        template_name (str): The template name to render for the page.

    Methods:
        get_context_data(**kwargs): Overrides the default get_context_data method to provide context data to the template.
    """

    template_name = "find_dogs.html"

    def get_context_data(self, **kwargs):
        """
        Provide context data to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for rendering the template.
        """

        context = super().get_context_data(**kwargs)

        dogs = Animal.objects.filter(
            species__iexact="dog", is_available_for_adoption=True
        )

        show_species = False
        filter_form = AnimalFilterForm(self.request.GET, show_species=show_species)
        if filter_form.is_valid():
            breed = filter_form.cleaned_data.get("breed")
            gender = filter_form.cleaned_data.get("gender")
            size = filter_form.cleaned_data.get("size")
            color = filter_form.cleaned_data.get("color")
            min_age = filter_form.cleaned_data.get("min_age")
            max_age = filter_form.cleaned_data.get("max_age")
            location = filter_form.cleaned_data.get("location")

            if breed:
                dogs = dogs.filter(breed__icontains=breed)
            if gender:
                dogs = dogs.filter(gender=gender)
            if size:
                dogs = dogs.filter(size=size)
            if color:
                dogs = dogs.filter(color__icontains=color)
            if min_age:
                dogs = dogs.filter(age__gte=min_age)
            if max_age:
                dogs = dogs.filter(age__lte=max_age)
            if location:
                dogs = dogs.filter(location=location)

        context["dogs"] = dogs
        context["filter_form"] = filter_form
        return context


class FindOtherPetsView(TemplateView):
    """
    A view for finding and filtering available pets of species other than cats and dogs.

    Attributes:
        template_name (str): The template name to render for the page.

    Methods:
        get_context_data(**kwargs): Overrides the default get_context_data method to provide context data to the template.
    """

    template_name = "find_other_pets.html"

    def get_context_data(self, **kwargs):
        """
        Provide context data to the template.

        Args:
            **kwargs: Additional keyword arguments.

        Returns:
            dict: A dictionary containing context data for rendering the template.
        """

        context = super().get_context_data(**kwargs)

        other_pets = (
            Animal.objects.filter(is_available_for_adoption=True)
            .exclude(species__iexact="cat")
            .exclude(species__iexact="dog")
        )

        show_species = False
        filter_form = AnimalFilterForm(self.request.GET, show_species=show_species)
        if filter_form.is_valid():
            color = filter_form.cleaned_data.get("color")
            breed = filter_form.cleaned_data.get("breed")
            gender = filter_form.cleaned_data.get("gender")
            size = filter_form.cleaned_data.get("size")
            min_age = filter_form.cleaned_data.get("min_age")
            max_age = filter_form.cleaned_data.get("max_age")
            location = filter_form.cleaned_data.get("location")

            if color:
                other_pets = other_pets.filter(color__icontains=color)
            if breed:
                other_pets = other_pets.filter(breed__icontains=breed)
            if gender:

pet_adoption/pet/templates/add_adoption_story.html
{% extends 'base.html' %} {% load bootstrap %} {% block content %}
<div class="container">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<h2>Add Adoption Story</h2>
			<form method="post">
				{% csrf_token %} {{ form|bootstrap }}

				<button type="submit" class="btn btn-primary mt-3">Submit</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

pet_adoption/pet/templates/adopted_animals.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
  <h2>Animals Adopted by You</h2>
  
  {% if adoptions %}
    <table class="table align-middle">
      <thead>
        <tr>
          <th>Image</th>
          <th>Animal Name</th>
          <th>Application Date</th>
          <th>Application Text</th>
          <th>Service</th>
          <th>Treatment</th>
        </tr>
      </thead>
      <tbody>
        {% for adoption in adoptions %}
          <tr>
            <td>
              <img src="{{ adoption.animal.image.url }}" class="adopted_animal_image">
            </td>
            <td>{{ adoption.animal.name }}</td>
            <td>{{ adoption.application_date }}</td>
            <td>{{ adoption.application_text }}</td>
            <td>
              <a href="{% url 'services' adoption.animal.pk %}" class="btn btn-outline-success btn-sm">Services</a>
            </td>
            <td>
              <a href="{% url 'treatments' adoption.animal.pk %}" class="btn btn-outline-success btn-sm">Treatments</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>You haven't adopted any animals yet.</p>  
  {% endif %}
  
  <a href="{% url 'home' %}" class="mt-3 d-block">Back to Home</a>
</div>


{% endblock %}

pet_adoption/pet/templates/adoption_stories.html
{% extends 'base.html' %} {% load bootstrap %} {% load static %}

{% block content %}

<div class="container adoption-stories">
	<div class="fancy-text">
		<h4 class="donate-heading mt-5 mb-4">Your Pet's Happiness is Guaranteed</h4>
		<p>
			We stand by our commitment to finding the best homes for our pets. Our
			100% Adoption Guarantee means that if the pet you choose isn't the perfect
			fit for your family, you can bring them back to us at any point in their
			life, no questions asked.
		</p>
		<p>Join the happy adopters who have given pets a loving home.</p>
	</div>

	{% if adoption_stories %}
	<div class="row row-cols-1 row-cols-lg-4 g-5 py-5">
		{% for story in adoption_stories %}
		<div class="col">
			<div class="adoption_story-card">
				<img
					class="user-img"
					src="{{ story.adoption.user.profile_picture.url }}"
					alt="{{ story.adoption.user.first_name }}"
				/>
				<img
					class="animal-img"
					src="{{ story.adoption.animal.image.url }}"
					alt="{{ story.adoption.animal.name }}"
				/>
				<div class="card-body adoption-story-body">
					<h2 class="card-title">
						{{ story.adoption.animal.name }}<span class="found-home-text"></span>
					</h2>
					<p>{{ story.story_title }}</p>
					<p>{{ story.story_description }}</p>
					<p class="mb-0">
						Adopted by: {{ story.adoption.user.first_name }} {{ story.adoption.user.last_name }}
					</p>
					<p class="mb-0">
						Location: {{ story.adoption.user.location }}
					</p>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>	
	{% else %}
	<p class="my-5">We don't have any adoption stories yet.</p>
	{% endif %} 
</div>

{% endblock %}

pet_adoption/pet/templates/application.html
{% extends 'base.html' %}

{% block content %}
    <h2>Your adoption applications</h2>
    <ul>
        {% for application in applications %}
            <li>
                {{ application.get_status_display }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

pet_adoption/pet/templates/available_services.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
	<a
		href="{% url 'create_service' animal.pk %}"
		class="btn btn-sm btn-warning mb-3"
		><i class="bi bi-plus-circle"></i> Add Service</a
	>

	<h2>Performed Services:</h2>

	{% if services %}
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Service Name</th>
				<th>Current Date</th>
				<th>Description</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			{% for service in services %}
			<tr>
				<td>{{ service.service_name }}</td>
				<td>{{ service.created_at.date }}</td>
				<td>{{ service.description }}</td>
				<td>$ {{ service.price }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<p>No services are performed for this animal.</p>
	{% endif %}

	<a href="{% url 'my_pets' %}" class="btn btn-secondary my-3"
		>Back to My Pets</a
	>
</div>
{% endblock %}

pet_adoption/pet/templates/available_treatments.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container">
	<a
		href="{% url 'create_treatment' animal.pk %}"
		class="btn btn-sm btn-warning mb-3"
		><i class="bi bi-plus-circle"></i> Add Treatment</a
	>

	<h2>Performed Treatments:</h2>

	{% if treatments %}
	<table class="table table-hover">
		<thead>
			<tr>
				<th>Treatment Name</th>
				<th>Current Date</th>
				<th>Next Date</th>
				<th>Notes</th>
			</tr>
		</thead>
		<tbody>
			{% for treatment in treatments %}
			<tr>
				<td>{{ treatment.treatment_name }}</td>
				<td>{{ treatment.created_at.date }}</td>
				<td>{{ treatment.next_date }}</td>
				<td>{{ treatment.description }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<p>No treatments are performed for this animal.</p>
	{% endif %}

	<a href="{% url 'my_pets' %}" class="btn btn-secondary mt-3"
		>Back to My Pets</a
	>
</div>
{% endblock %}

pet_adoption/pet/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<title>AdoptMe</title>
		<meta name="description" content="Our first page" />
		<meta name="keywords" content="html tutorial template" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
			crossorigin="anonymous"
		/>
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css"
		/>
		<link rel="stylesheet" href={% static 'css\styles.css' %}>
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap"
			rel="stylesheet"
		/>
	</head>
	<body class="d-flex flex-column min-vh-100">
		<nav
			class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top border-bottom"
		>
			<div class="container">
				<a class="navbar-brand" href="{% url 'home' %}"
					><i class="bi bi-house-heart"></i> AdoptMe</a
				>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarNav"
					aria-controls="navbarNav"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div
					class="collapse navbar-collapse justify-content-between mx-5"
					id="navbarNav"
				>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a
								class="nav-link"
								aria-current="page"
								href="{% url 'adoption_stories' %}"
								>Adoption Stories</a
							>
						</li>
						<li class="nav-item">
							<a class="nav-link" aria-current="page" href="{% url 'donate' %}"
								>Donate</a
							>
						</li>
						<li class="nav-item">
							<a class="nav-link" aria-current="page" href="{% url 'about' %}"
								>About</a
							>
						</li>
						<li class="nav-item mx-5">
							<form class="d-flex" method="GET" action="{% url 'animal_search' %}">								
								<input class="form-control me-2"
								 type="search" placeholder="Species | Breed | Name"
								 aria-label="Search"
								 name="searched">
								<button class="btn btn-outline-success" type="submit">Search</button>
							</form>
						</li>
					</ul>

					<div class="navbar-nav">
						{% if user.is_authenticated %}
						<div class="user-info">
							<span class="user-name"
								>{{ user.first_name }} {{ user.last_name }}</span
							>
						</div>
						<div class="nav-item dropdown">
							<a
								class="nav-link dropdown-toggle"
								href="#"
								id="profileDropdown"
								role="button"
								data-bs-toggle="dropdown"
								aria-expanded="false"
							>
								<img
									src="{{ user.profile_picture.url }}"
									alt="User Profile"
									class="rounded-circle"
									style="width: 50px; height: 50px; object-fit: cover"
								/>
							</a>
							<ul
								class="dropdown-menu"
								data-bs-theme="dark"
								aria-labelledby="profileDropdown"
							>
								{% if user.is_authenticated and user.is_superuser %}
								<li>
									<a class="dropdown-item border-bottom" href="{% url 'adoption_pending_list'%}">Pending Forms (Admin)</a>
								</li>
								{% endif %}
								<li>
									<a class="dropdown-item" href="{% url 'animal_favourite_list' %}">Favourite Pets</a>

								</li>								
								<li>
									<a class="dropdown-item" href="{% url 'my_adoption_forms'  %}">My Adoption Forms</a>
								</li>
								<li>
									<a class="dropdown-item" href="{% url 'my_pets' %}"
										>My Pets</a
									>
								</li>
								<li>
									<a class="dropdown-item border-bottom" href="{% url 'accounts:userprofile_detail' pk=user.id%}">User Profile</a>
								</li>
								<li>
									<a class="dropdown-item" href="{% url 'accounts:logout' %}"
										>Sign Out</a
									>
								</li>
							</ul>
						</div>
						{% else %}

						<div class="navbar-nav me-auto mb-2 mb-lg-0">
							<a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}"
								>Login</a								
							>
							<a class="nav-link" aria-current="page" href="{% url 'accounts:register' %}"
							>SignUp</a
						>
						</div>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>


		{% block banner %}
		<div class="banner-home">
			<img
				src="https://www.petfinder.com/sites/default/files/styles/hero_image_1140_410/public/images/content/1140%20hero%20image_0.jpg?itok=wryBzVcI"
				alt="Cat or Dog Image"
				class="banner-image"
			/>
			<div class="banner-text">
				<h1>Find your new best friend</h1>
				<p>Browse pets from our network of over 100 shelters and rescues.</p>
			</div>
		</div>
		{% endblock %}

		<div class="container flex-grow-1">{% block content %} {% endblock %}</div>



			<footer class="py-3 mt-5 bg-dark" data-bs-theme="dark">
				<ul class="nav justify-content-center border-bottom pb-3 mb-3">
				  <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
				  <li class="nav-item"><a href="{% url 'adoption_stories' %}" class="nav-link px-2 text-body-secondary">Adoption Stories</a></li>
				  <li class="nav-item"><a href="{% url 'donate' %}" class="nav-link px-2 text-body-secondary">Donate</a></li>
				  <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-body-secondary">About</a></li>
				</ul>
				<p class="text-center text-body-secondary">Created by the Group_1 (SDA_ZDPYTpol70) · © 2023</p>
			</footer>


		</div>

		<!-- Include Bootstrap JavaScript file -->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
			crossorigin="anonymous"
		></script>

		<!-- Include scripts.js JavaScript file -->
		<script src="{% static 'scripts/scripts.js' %}"></script>
	</body>
</html>

pet_adoption/pet/templates/create_adoption.html
{% extends 'base.html' %} {% load bootstrap %} {% block content %}
<h1>Create Adoption Form</h1>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %} {{ form|bootstrap }}
	<button type="submit" class="btn btn-success mt-3">Submit</button>
</form>
{% endblock %}

pet_adoption/pet/templates/create_treatment.html
{% extends 'base.html' %} {% load bootstrap %} {% block content %}
<h1>Create Treatment</h1>
<form method="post" enctype="multipart/form-data">
	{% csrf_token %} {{ form|bootstrap }}
	<button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>
{% endblock %}

pet_adoption/pet/templates/donate.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div
	id="user-data"
	data-logged-user="{{ logged_user }}"
	style="display: none"
></div>

<div class="fancy-container mb-5">
	<div class="fancy-text">
		<div class="fancy-heading">We’re On a Mission to Save More Lives</div>
		<p>
			In 2023, the Programing Guys Society decided that the impact we had been
			making for 60 years could be even bigger. We set out with an ambitious
			goal to end animal suffering, homelessness and needless euthanasia in
			Maricopa County. We made strategic partnerships, and implemented a host of
			innovative new programs. And the numbers are in: It’s working.
		</p>

		<p>150,000 More Pets Saved</p>
		<p>
			Since 2022, we’ve reduced euthanasia by 83%. That’s 150,000 additional
			lives saved. Our trauma hospital and rescue and cruelty investigations
			team save thousands of dogs, cats, and critters every year. Our Mutternity
			Suites, Kitten Nursery, Bottle Baby ICU and Parvo Puppy ICU care for the
			pets who would be quickly euthanized in other shelters. And every day,
			we’re providing our community with affordable veterinary care and
			financial assistance to keep more pets in homes.
		</p>
	</div>
	<div class="fancy-image">
		<img
			src="https://img.freepik.com/premium-photo/human-dog-make-heart-shape-with-his-hands-paw_3579-2760.jpg?w=450"
			style="box-shadow: 0px 5px 10px rgba(0, 0, 0, 0.25); border-radius: 5px"
		/>
	</div>
</div>

<div class="donate-container">
	<div class="donate-heading">Give Now</div>

	<div class="donate-amounts">
		<div class="donate-amount" data-amount="5">$5</div>
		<div class="donate-amount" data-amount="10">$10</div>
		<div class="donate-amount" data-amount="50">$50</div>
		<div class="donate-amount" data-amount="100">$100</div>
		<input
			class="donate-amount custom-amount"
			type="number"
			placeholder="Custom Amount $"
		/>
	</div>

	<button class="donate-button">Donate</button>

	<div class="donate-success" id="success-message"></div>
</div>
{% endblock %}